#!/usr/bin/env python

import sys
import os
import subprocess
import glob
import re
from aptdaemon import lock
import time

STATE_FILE="/var/tmp/capers_state"
BLACK_LISTS_DIR="/etc/blacklist.d"
BLACK_LISTS_FILE="/etc/blacklists"
PRIORITY_APPS=['capers']
APP_INSTALL_DESKTOP_DIR = "/usr/share/app-install/desktop"
HOLD_LIST = "/etc/capers-hold"

def touch(filename, times=None):
    with file( filename, 'a'):
        os.utime(filename, times)

class Cache( ):
    def __init__( self ):
        self.perform_update()

    def hold_packages( self ):
        f = open( HOLD_LIST, 'r' )
        for line in f:
            p1 = subprocess.Popen(['echo',line + ' hold'], stdout=subprocess.PIPE)
            p2 = subprocess.Popen(['dpkg','--set-selections'], stdin=p1.stdout, stdout=subprocess.PIPE)

    def perform_update( self ):
        subprocess.call( ['apt-get','update'],stdout=subprocess.PIPE )

    def full_clean( self ):
        subprocess.call( ['dpkg','--configure','-a'], stdout=subprocess.PIPE )
        subprocess.call( ['apt-get','install','-f','-y','--force-yes'], stdout=subprocess.PIPE )
        subprocess.call( ['apt-get','autoremove','-y','--force-yes'], stdout=sys.stdout )

    def blacklist_apps( self ):
        self.refresh_blacklists()
        self.blacklist_applications( self.read_blacklists() )

    def refresh_blacklists( self ):
        blacklist_file = open( BLACK_LISTS_FILE, 'r' )
        blacklists = blacklist_file.read()
        blacklist_file.close()        
        subprocess.call( ['apt-get','install','--reinstall','-y','--force-yes'] + blacklists.split() )

    def read_blacklists( self ):
        return_value = []
        for blacklist in glob.glob( BLACK_LISTS_DIR + '/*' ):
            f = open( blacklist, 'r' )
            for line in f:
                line = line.strip()
                if line != "":
                    return_value.append( line.strip() )
        return return_value

    def blacklist_applications( self, packages ):
        if packages:
            #Removing from apt indexes (code refraction for speed)
            self.remove_from_apt_index( packages )
            for package in packages:
                try:
                    if subprocess.check_output( ['dpkg','-l',package] ).split('\n')[-2].startswith('ii'):
                        print "REMOVING " + package
                        subprocess.call( ['apt-get','purge',package,'-y','--force-yes'] )
                except:
                    pass
            #apt indexes
                    counter = 0
            #software centre indexes
            for package in packages:
                self.remove_from_sc_index( package )
            subprocess.call( [ 'update-software-center' ] )

    def acquire_apt_lock( self ):
        for i in range(0, 100):
               try: 
                  lock.acquire()
                  return True
               except lock.LockFailedError as error:
                  print "Someone is holding the apt lock, sleeping until they release it"
                  time.sleep(5)
        return False

    def remove_from_sc_index( self, package_name ):
            os.chdir( APP_INSTALL_DESKTOP_DIR )
            desktop_files = os.listdir( "." )
            for desktop_file in desktop_files:
                if desktop_file.startswith( package_name + ":" ):
                    os.remove( desktop_file )
    
    def remove_from_apt_index( self, packages ):
        t0 = time.time()
        print "Removing blacklisted packages from index files"
        # acquire the lock before modifying the files
        if not self.acquire_apt_lock():
            print "Unable to get the apt lock, not removing packages from index"
            return
        else:
            for file_name in os.listdir( "/var/lib/apt/lists" ):
                file_name = "/var/lib/apt/lists/" + file_name
                if ( os.path.isfile( file_name ) ) and ( file_name != "/var/lib/apt/lists/lock" ):
                    index_file = open( file_name, 'r' )
                    file_in_mem = index_file.read()
                    index_file.close()
                    for package_name in packages:
                        if file_in_mem.find( "Package: " + package_name  ) > -1:
                            index_file = open( file_name, 'w' )
                            lines = file_in_mem.split( "\n" )
                            counter = -1
                            while counter < len( lines )-1:
                                counter = counter + 1
                                if "Package: " + package_name == lines[ counter ].strip():
                                    while lines[ counter ].strip() is not "":
                                        counter=counter + 1
                                index_file.write( lines[ counter ] + "\n" )
                            index_file.close()
        t1 = time.time()
        print "finished in %f" % (t1 - t0)
        lock.release()


def clean_up_kernels():
    kernel_versions = []
    for kernel in glob.glob('/boot/vmlinuz*'):
        kernel_versions.append( re.findall( '[0-9]\.[0-9]\.[0-9]-[0-9][0-9]', kernel)[0] )
    remove_packages = []
    for version in kernel_versions:
        if version < max( kernel_versions ):
            remove_packages.append( "linux-headers-" + version )
            remove_packages.append( "linux-image-" + version )
    if remove_packages:
        subprocess.call( ['apt-get','purge','-y','--force-yes'] + remove_packages )

def main( argv ):
    # make a "running" file. This allows for an interrupted operation to be catered for.
    touch( STATE_FILE )
    cache = Cache()
    cache.full_clean()
    cache.blacklist_apps()
    os.remove( STATE_FILE )
    #Download files
    subprocess.call(['apt-get','-d','dist-upgrade','-y','--force-yes'])
    touch( STATE_FILE )
    #Apply updates
    if subprocess.call(['apt-get','dist-upgrade','-y','--force-yes']) == 0:
        subprocess.call(['apt-get','clean'])
    clean_up_kernels()
    os.remove( STATE_FILE )

if __name__ == "__main__":
    os.environ["DEBIAN_FRONTEND"]="noninteractive"
    main(sys.argv[1:])
